### PR TITLE
Split model wizards

### PR DESCRIPTION
**Pull request by nboldi**

### CODE REVIEW

**Comment by nboldi** [comment]
@devaigergely81, please test.
Container and package is guessed from selection. Please also validate that.

**Comment by devaigergely81** [comment]
I suggest to fix #175 before merging. Other than that, I think it is all right.

**Comment by nboldi** [comment]
Note that I removed the {txtUML} image from the wizards because it slided out of the view when a validation error appeared.

**Comment by kovacsgabor** [comment]
The wizard only lets valid Java identifiers as model names but txtUML models may now have any name that is allowed in EMF-UML2.

**Comment by kovacsgabor** [comment]
If package ```x.y``` is a model, the wizard still allows me to create a model 'above' it in package ```x```.

**Comment by kovacsgabor** [comment]
Only a proposal, but I would prefer the XtxtUML syntax to be default.

**Comment by kovacsgabor** [comment]
I created an issue that is connected to this branch: #182.

**Comment by devaigergely81** [comment]
We have to think about it, but having a model in another model (eg. both in packages x and x.y) might not be a problem.

**Comment by devaigergely81** [comment]
#175 is now solved on this branch. I will merge this and create issues about kovacsgabor's suggestions above.

**Pull request merged**
