### PR TITLE
Hidden composition

### PR DESCRIPTION
**Pull request by kovacsgabor**
Introducing non-navigable container ends of compositions to the language.

Implemented the JtxtUML part. @kmate, please implement the XtxtUML part as well before merging this branch.

### CODE REVIEW

**Comment by kmate** [comment]
@nboldi can you check and merge this branch please?

**Comment by kmate** [comment]
Jenkins retest this please

**Comment by kmate** [comment]
The build is failing because of an xtend bug. I will patch it in the next commit.

**Comment by nboldi** [comment]
Seems to be the thing I expected.

**Pull request merged**
