### PR TITLE
UI improvements in XtxtUML

### LINKED ISSUE #20: Enhance XtxtUML formatting
Now the formatter emits a single line, and only wraps it when it is longer than 80 characters. Implement a custom formatter.

### PR DESCRIPTION
**Pull request by djnemeth**
This pull request introduces new or improved UI features, which are intended to make XtxtUML more convenient to use. For a brief overview, see the (full) commit messages. This resolves #20.

**The new features in action:**
(Click on the images to enlarge.)

- Content assist.
  
  | Before | After |
  | :---: | :---: |
  | content_assist_before  | content_assist_after|
  | jvm_content_assist_before | jvm_content_assist_after  |

- Linking-related error message and import quickfix.
  
  | Before | After |
  | :---: | :---: |
  | unresolved_before  | unresolved_after |

- Import organizer. 
  
  |  import_sort_before |  Ctrl + Shift + O<br>———————>  | import_sort_after  |
  | :---: | :---: | :---: |
  | import_rewrite_before | **Ctrl + Shift + O<br>———————>**   |   import_rewrite_after_plus <br> **+** <br> import_rewrite_after  |

- Auto formatting.
  
  | format_before  | Ctrl + Shift + F<br>———> |  format_after |
  | :---: | :---: | :---: |

### CODE REVIEW

**Comment by djnemeth** [comment]
@devaigergely81 and @kmate, please review.

**Comment by kmate** [comment]
The import organizer brings in unnecessary imports in some cases. For example, in the [incorrect inference project](https://github.com/ELTE-Soft/txtUML/files/200984/incorrect-inference.zip), it adds the following:

~~~~
import incorrect.inference.A.Init;
import incorrect.inference.A.P;
~~~~

But these are defined in the same source file, so no import necessary.

The other things seem to work, but this branch added a huge amount of new code and I have not checked it line-by-line.

**Comment by djnemeth** [comment]
I believe this is somehow related to how Xbase handles inner classes. See, for example #89.

**Comment by djnemeth** [comment]
This branch requires further fixes and improvements, therefore I close this pull request for now.

**Comment by djnemeth** [comment]
The reopened pull request introduces several fixes and further improvements. See the (full) commit messages for details.

**The new features in action:**
(Click on the images to enlarge.)

- Improved highlighting of attributes, formal parameters, documentation comments and multiplicities.
  
  | Before | After |
  | :---: | :---: |
  | highlighting_before | highlighting_after |

- XtxtUML execution elements are now directly runnable from the package and project explorer.

  launch_execution

**Comment by djnemeth** [comment]
@kovacsgabor, please review the new changes.
@dobreffandras, please have a quick look at the changed [plugin.xml](https://github.com/ELTE-Soft/txtUML/pull/312/commits/53c7de765c240b59ace078fc1b20aae0d6dadb8b#diff-2beb002c1f8faa9eb20fcee6a4fc3877) to ensure its sanity.

**Comment by dobreffandras** [comment]
I have no idea about these adapter factories, but the launch shortcuts extension point seems to be good :D
What kind of files have *.txtuml extension btw?

Syntax highlight and auto format are good, so I also think #20 is resolved.

Somehow as i tried to write a constructor for `Engine` in the train model, i did not get the content assist for `this.i` 

```java
class Engine {
	int i;
	/*...*/
	public Engine(int i) {
		this.i = i;
	}
        /*...*/
}
```

**Comment by djnemeth** [comment]
1. *.txtuml* is just an alternative extension for XtxtUML files. Maybe we should discuss if we want to support it in the future. As far as I know, in the current implementation the two extension are interchangeable, apart from one notable exception: the *model-info* file *must* have the *.xtxtuml* extension, see the [file validator](https://github.com/ELTE-Soft/txtUML/blob/d4ffa9ec389c42460a49e9d3bf814c42a54be67c/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/validation/XtxtUMLFileValidator.xtend#L18). (Personally, I consider this as a flaw of our validation, and as such, it should be fixed.)

2. The missing content assist in case of feature calls is originating from the grammar. For some reason, incomplete feature calls are parsed as [declaration prefixes](https://github.com/ELTE-Soft/txtUML/blob/d4ffa9ec389c42460a49e9d3bf814c42a54be67c/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L92), therefore the expected content assist components are not even called. This could be resolved only by restructuring the grammar.

**Pull request merged**
