### PR TITLE
Airport demo fixes

### PR DESCRIPTION
**Pull request by nboldi**
Added Airport example to the project.
Corrected Airport example to work with current master.
Corrected master to support calling `selectAny` on empty collection.
Corrected export to support exporting `.equals` and `.equal` calls (generated by Xtext), and to support exporting use of classes from standard library.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
One of the unit tests in `export.uml2` broke. @nboldi, cold you take a look at it?

**Comment by nboldi** [comment]
Sorry, forgot to update that unit test. Should be OK now.

**Comment by kovacsgabor** [comment]
@nagyandras95, please check your local git settings, because your last commit is not attached to your account.

**Comment by kovacsgabor** [comment]
I did not review the example's code, but it works and the other changes are all fine. As soon as the check is performed and is successful, this pull request can be merged.

**Pull request merged**
