### PR TITLE
Uml export structural improvements

### LINKED ISSUE #358: Export InPort and OutPort

### LINKED ISSUE #359: Export Interface.Empty

### PR DESCRIPTION
**Pull request by nboldi**
Export for InPort and OutPort as well as Interface.Empty interfaces.
 - Resolves #358 
 - Resolves #359

### CODE REVIEW

**Comment by kovacsgabor** [comment]
Ready to be merged as soon as the check completes.

**Comment by kovacsgabor** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Pull request merged**
