### PR TITLE
Getting rid of moka

### PR DESCRIPTION
**Pull request by gerazo**
Fix for this: https://github.com/ELTE-Soft/txtUML/issues/193
All dependencies and target settings were removed for Moka. I hope it will make the whole thing a degree lighter.

### CODE REVIEW

**Comment by gerazo** [comment]
Please review @devaigergely81, @kmate, @kovacsgabor or anybody who feels empowered.

**Comment by kmate** [comment]
I removed moka from associate sites too with the previous commit. It looks that the diagram animation works in general, but I found two problems:
1. Initial pseudo-states are not highlighted.
2. The markers remain on diagram after the execution is terminated because either the model execution ended or either it was terminated by the user.

I did not tested the update site, I used a guest eclipse.

**Comment by gerazo** [comment]
Thanks @kmate I will check the two items mentioned. I will try to find out what extra functionality is present in the original which can remedy these issues.

**Comment by gerazo** [comment]
Sometimes it is not working at all. It seems like some stylesheets are missing and without moka, nothing happens on sending the markers. I have to thoroughly check on a fresh install but if that is the case, we have to access editor parts directly. :-1:

**Pull request closed without merging**
