### PR TITLE
Modify binding of `this` and `super` => add `else` and `sigdata`

### LINKED ISSUE #26: The expression `this` cannot be typed in action of state or transition
The following code:
```
model ErrorReportingModel {
	class A {
		state A1 {
			entry {
				send new S() to this;
			}
		}
	}
	signal S;
}
```
Gives the error message
```Type mismatch: cannot convert the expression to Class```

### PR DESCRIPTION
**Pull request by djnemeth**
For a brief overview, see the (full) commit messages.

The type computation of the `sigdata` expression is *almost* identical to the rAlf specification, that is:

>The type of the `sigdata` data structure is depending on the state machine structure. In case of a transition with one trigger the type of the `sigdata` data structure is always the signal triggering the given transition. In case of multiple triggers the type of the `sigdata` is the effective common ancestor of all signals triggering the given transition. If no common ancestor is found then the type will be *any*. The rule is similar for entry and exit actions but instead of triggers the incoming and outgoing transitions are taken into consideration respectively.

The following differences are present in this implementation:
- multiple triggers are not considered,
- if no common ancestor is found, the type will be the `Signal` defined in JtxtUML (which is technically a common ancestor for all signals after all).

This is intended to fix #26.

### CODE REVIEW

**Comment by djnemeth** [comment]
@devaigergely81 and @kovacsgabor, please review.

**Comment by kovacsgabor** [comment]
:+1: I approve.

**Comment by kovacsgabor** [comment]
@kmate, please review.

**Comment by kmate** [comment]
Something very strange happens here.. I am able to build the modified examples but the error log contains interesting items like:

Description	Resource	Path	Location	Type
null - See error log for details	XtxtUMLCompiler.xtend	/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/compiler	line 1	Xtext Check (normal)

I also have a stack trace from the console of the guest process:
```
!ENTRY org.apache.log4j 4 0 2015-11-17 16:27:44.092
!MESSAGE org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLTypeComputer.xtend'.

!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.runtime.Path.append(Path.java:261)
	at org.eclipse.xtext.builder.JDTAwareEclipseResourceFileSystemAccess2.addToSourceFolders(JDTAwareEclipseResourceFileSystemAccess2.java:66)
	at org.eclipse.xtend.ide.builder.SourceRelativeFileSystemAccess.ensureOutputConfigurationDirectoryExists(SourceRelativeFileSystemAccess.java:29)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:259)
	at org.eclipse.xtext.generator.AbstractFileSystemAccess2.generateFile(AbstractFileSystemAccess2.java:28)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$7.apply(ParallelFileSystemAccess.java:141)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$7.apply(ParallelFileSystemAccess.java:1)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$1.apply(ParallelFileSystemAccess.java:57)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doBuild(ParallelBuilderParticipant.java:128)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:221)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:252)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
After further investigation I found that it wants to rebuild the machine project using the following resource set:
```
ToBeBuilt [
	toBeUpdated=[platform:/resource/hu.elte.txtuml.examples.machine/src/hu/elte/txtuml/examples/machine/XMachine3.xtxtuml, platform:/resource/hu.elte.txtuml.examples.machine/src/hu/elte/txtuml/examples/machine/XMachine2.xtxtuml, platform:/resource/hu.elte.txtuml.examples.machine/src/hu/elte/txtuml/examples/machine/XMachine1.xtxtuml, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/highlighting/XtxtUMLHighlightingCalculator.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/validation/XtxtUMLValidator.xtend, platform:/resource/org.eclipse.uml2.uml/org/eclipse/uml2/uml/internal/impl/uml.ecore, platform:/resource/org.eclipse.uml2.uml/model/UML.ecore, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/naming/XtxtUMLQualifiedNameConverter.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/scoping/XtxtUMLImplicitlyImportedFeatures.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLReentrantTypeResolver.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/validation/XtxtUMLExpressionHelper.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/XtxtUML.xtext, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLTypeComputer.xtend, platform:/resource/org.eclipse.uml2.uml/model/CMOF20.ecore, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/contentassist/XtxtUMLProposalProvider.xtend, platform:/resource/org.eclipse.uml2.uml/model/UML30.ecore, platform:/resource/.org.eclipse.jdt.core.external.folders/.link9/hu/elte/txtuml/xtxtuml/lib/std.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/formatting/XtxtUMLFormatter.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/outline/XtxtUMLOutlineTreeProvider.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/scoping/XtxtUMLXImportSectionNamespaceScopeProvider.xtend, platform:/resource/org.eclipse.uml2.uml/model/CMOF241.ecore, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLEarlyExitComputer.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/quickfix/XtxtUMLQuickfixProvider.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/GenerateXtxtUML.mwe2, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/labeling/XtxtUMLDescriptionLabelProvider.xtend, platform:/resource/org.eclipse.uml2.uml/model/CMOF.ecore, platform:/resource/org.eclipse.uml2.uml/model/CMOF24.ecore, platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/labeling/XtxtUMLLabelProvider.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/jvmmodel/XtxtUMLJvmModelInferrer.xtend, platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/compiler/XtxtUMLCompiler.xtend],
	toBeDeleted=null
]
```

**Comment by kmate** [comment]
I was unable to reproduce the above error on Eclipse Mars.

**Pull request merged**
