### PR TITLE
Removed unnecessary dependencies of test projects

### LINKED ISSUE #188: Dependency cycles caused by test projects
When exporting txtUML as a Deployable feature with all test projects imported in the workspace, the exportation fails because of one of the following two dependency cycles it finds:

hu.elte.txtuml.api.model
hu.elte.txtuml.api.stdlib

and

hu.elte.txtuml.xtxtuml
hu.elte.txtuml.xtxtuml.ui

### PR DESCRIPTION
**Pull request by kovacsgabor**
Fixes #188.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@djnemeth, please review.

**Comment by gerazo** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Comment by djnemeth** [comment]
:+1:
Sorry for the delayed review.

**Pull request merged**
