### PR TITLE
Configuring update sites correctly

### PR DESCRIPTION
**Pull request by gerazo**
Should fix https://github.com/ELTE-Soft/txtUML/issues/6

### CODE REVIEW

**Comment by gerazo** [comment]
Please review @djnemeth @devaigergely81

**Comment by djnemeth** [comment]
Unfortunately, I couldn't install the plugin automatically with a clean Luna. It still can't find the missing update sites:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: txtUML 0.1.1.201510271532 (hu.elte.txtuml.feature.feature.group 0.1.1.201510271532)
  Missing requirement: txtUML 0.1.1.201510271532 (hu.elte.txtuml.feature.feature.group 0.1.1.201510271532) requires 'org.eclipse.xtext 2.8.0' but it could not be found
```

However, the update sites specified in `feature.xml` have been added to the available software sites as I added the exported txtUML update site, but they are disabled by default:

update_sites

**Comment by gerazo** [comment]
So even if we generate these lines into the content.xml as you have specified it is still not enough. I will take a look.

**Comment by djnemeth** [comment]
I'm not sure if I have misunderstood your last comment, but the workaround I [proposed](https://github.com/ELTE-Soft/txtUML/issues/6#issuecomment-150872934) is about *manually* editing the `content.xml` *after* the plugin exportation is done. It's not very elegant indeed, but using that method I managed to install our plugin automatically.

**Comment by gerazo** [comment]
You didn't misunderstand and you are right. It is not elegant and suffers from the same problem if the repositories are already added. Worst case we can try creating a composite site... I will try.

**Comment by devaigergely81** [comment]
It fails also for me. If I manually enable the urls added in the first round, it installs everything automatically for the second try.

**Pull request closed without merging**
