### PR TITLE
Tests/papyrus

### PR DESCRIPTION
**Pull request by dobreffandras**
Unit tests added to DiagramManager class

### CODE REVIEW

**Comment by kovacsgabor** [comment]
ok to test

**Comment by kovacsgabor** [comment]
The tests are not run by Jenkins... is the test project configured properly?
(https://github.com/ELTE-Soft/txtUML/wiki/Creating-Projects#creating-a-test-project)

**Comment by dobreffandras** [comment]
I hope I corrected everything well. What about the pom.xml? There is a TODO in there.

**Comment by kovacsgabor** [comment]
I removed that block in the pom.xml to enable the tests and now all unit tests are run by Jenkins and they pass.

Note: I did not review the tests themselves.

**Comment by djnemeth** [comment]
@dobreffandras, I believe the mentioned TODO originated from #150.

**Comment by dobreffandras** [comment]
Thanks, I remembered this issue, but did not know if it is still relevant.

**Comment by kovacsgabor** [comment]
Yes, @djnemeth, your are right. I think this also means that #150 is fixed.

**Pull request merged**
