### PR TITLE
Repo layout change

### PR DESCRIPTION
**Pull request by gerazo**
The tests will fail until Jenkins is not set up correctly. I will only do this if the review is successful.
Please review @devaigergely81 @nboldi @kovacsgabor. If you like it DO NOT merge! I need to set Jenkins first.

Every example was moved to tests. Which should we put into demo? (Machine, Train, Monitoring, Producer Consumer only?)
https://github.com/ELTE-Soft/txtUML/issues/247

### CODE REVIEW

**Comment by nboldi** [comment]
tests should not go into the plugins directory, but remain in a tests directory under dev

**Comment by gerazo** [comment]
Sorry, I was confusing. Every example was put into examples/tests and some examples are waiting to be promoted into examples/demo because their quality is outstanding.

**Comment by nboldi** [comment]
.settings folders should not be versioned

**Comment by nboldi** [comment]
This renaming does not seem to be right:
tests/hu.elte.txtuml.utils.tests/.classpath → .../hu.elte.txtuml.api.deployment/.classpath

**Comment by gerazo** [comment]
.settings folders were always versioned before
The 2 files mentioned are identical so their hash is the same. Git thinks a different but equally good renaming combination compared to what I did. It is not a problem. Check out the repo and see if everything is still at the same place.

**Comment by nboldi** [comment]
It is strange that git still tries to figure out the renamings even that you manually renamed the files...
The history of identical files could be swapped by the different renaming combination.

**Comment by gerazo** [comment]
Yes, despite the fact that I used "git mv" to move. I think the only way to force distinction is to make all moves a separate commit... which I obviously don't want to do :pig:

**Comment by kovacsgabor** [comment]
https://git.wiki.kernel.org/index.php/GitFaq#Why_does_Git_not_.22track.22_renames.3F

> Git has a rename command git mv, but that is just for convenience. The effect is indistinguishable from removing the file and adding another with different name and the same content.

**Comment by gerazo** [comment]
So, can I consider it reviewed then? :question:

**Comment by nboldi** [comment]
OK for me. :+1:  But the `.settings` folders should not be versioned, so please remove them after the change. They contain eclipse view settings for example. I already added gitignores for them in several plugins.

**Comment by gerazo** [comment]
@nboldi Should I do it in a separate pr?

**Comment by gerazo** [comment]
And can I put Machine, Train, Monitoring, Producer Consumer into the demo folder?

**Comment by nboldi** [comment]
Yes, use a separate branch, or do it on the master.

**Comment by gerazo** [comment]
Ok, we can put the examples to the right place later as well. I start setting Jenkins up. Thanks :cocktail:

**Comment by gerazo** [comment]
retest this please

**Pull request merged**
