### PR TITLE
Validation refactor

### PR DESCRIPTION
**Pull request by kovacsgabor**
Simplifying the validation error message system.
Providing the ability to add other kinds of JtxtUML validation (other than model validation).

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@nagyandras95 or @djnemeth, could one of you review this, please? I think @dobreffandras won't have the time for it.

**Comment by djnemeth** [comment]
Sure, I'll take it.

**Comment by kovacsgabor** [comment]
@djnemeth, could you review this, please?

**Comment by djnemeth** [comment]
Jenkins, retest this, please.

**Comment by kovacsgabor** [comment]
retest this please

**Pull request merged**
