### PR TITLE
Getting rid of moka

### PR DESCRIPTION
**Pull request by gerazo**
Finally getting rid of Moka. Please review!
The new version uses our own CSS to parametrize the animation outlook.
See also the stylesheet itself: hu.elte.txtuml.diagnostics/css/txtUMLAnimation.css
There are multiple possibilities in it which do work. We should decide and fine tune according to which looks cooler. (for example the bold text sometimes looks weird with ill formed diagrams). Please review this as well! @kmate @devaigergely81 @kovacsgabor @GregoBalu @dobreffandras @djnemeth

### CODE REVIEW

**Comment by kmate** [comment]
works for me :+1:

**Comment by dobreffandras** [comment]
for me too. :D

**Comment by devaigergely81** [comment]
It works for me in guest Eclipse, but not in installed setup. My setup:
- Win7
- Eclipse 4.5 Java
- Download the update site zip file from Jenkins:
txtUML-getRidOfMoka/ws/releng/hu.elte.txtuml.updatesite/target/ (or build it locally --- I tried both)
- Install from the zip file
- Import the [sample projects](http://txtuml.inf.elte.hu/wiki/lib/exe/fetch.php?media=v030:sample_models.zip) into the workspace.
- Generate Papyrus diagrams from one of the models (I tried XTrain and Machine1).
- Set a debug config of type txtUML application for the selected model's tester.
- Start debug
- No animation is shown on the generated state diagrams.

**Comment by gerazo** [comment]
retest this please

**Comment by gerazo** [comment]
The css files were missing from the generated update site. Now it is working.

**Pull request merged**
