### PR TITLE
Minimized update site with feature dependencies

### PR DESCRIPTION
**Pull request by kmate**
This branch is intended to minimize the update site size by removing transitive dependencies. It also solves #117, see more details there. @gerazo @devaigergely81 can you check that the update site generated by this build works correctly?

### CODE REVIEW

**Comment by kmate** [comment]
Jenkins retest this please

**Comment by kmate** [comment]
Unfortunately it seems that the pull request builder does not work with a branch that once had its own Jenkins job... I suggest to check out the branch and build it with maven locally, the try out the created update site.

**Comment by gerazo** [comment]
You've deleted the branch

**Comment by kmate** [comment]
Something went wrong... I will restore it soon, sorry...

**Pull request closed without merging**
