### PR TITLE
Generate Xtext also automatically

### PR DESCRIPTION
**Pull request by gerazo**
1. Every generated content is out of the repo.
2. Maven generates Xtext related stuff automatically in the build process.
3. The exact same stuff is generated as using Eclipse.
4. Manifest modification is disabled so git does not complain about modified manifests all the time
(In case of Xtext/Xtend version upgrade /which would be beneficial now I think/, the manifests can be merged by hand as the generated one is put next to the original.)
5. In case of a fresh checkout in Eclipse you still need to manually execute the "Generate Language Infrastructure" or do a maven build launch

### CODE REVIEW

**Comment by gerazo** [comment]
Please review @djnemeth @kmate @devaigergely81

**Comment by gerazo** [comment]
Related issue: https://github.com/ELTE-Soft/txtUML/issues/186

**Comment by gerazo** [comment]
You can also review @nboldi :)

**Comment by nboldi** [comment]
I could not find the `Generate Language Infrastructure` launch, and `Maven generate-sources` was not successful, but after a `clean-verify` and some refreshing everything worked fine. I suggest that doing a `clean-verify` should be the standard procedure for generating the sources.

So in general, it seems to be fine.

**Pull request merged**
