### PR TITLE
A warning message box is displayed if there is no description provided

### PR DESCRIPTION
**Pull request by dobreffandras**
#85 solved

### CODE REVIEW

**Comment by kovacsgabor** [comment]
jenkins retest this please

**Comment by devaigergely81** [comment]
The warning message should not appear if the "Generate state machines diagrams automatically" checkbox is checked, because in that case diagrams are indeed generated even if no diagram descriptions are selected. (I know that the checkbox will go away when the state machine visualization branch gets merged, but we should keep the master branch consistent any time.)

I would add the following text to the warning: "Use the 'Add txtUML diagram descriptions' button to avoid this message."
And the question at the end could be: "Do you want to continue without diagram descriptions?"

**Comment by kovacsgabor** [comment]
jenkins retest this please

**Comment by dobreffandras** [comment]
jenkins retest this please

**Comment by kovacsgabor** [comment]
ok to test

**Comment by kovacsgabor** [comment]
retest this please

**Comment by devaigergely81** [comment]
Looks good and works fine. Thx.

**Comment by devaigergely81** [comment]
jenkins retest this please

**Pull request merged**
