### PR TITLE
Examples refactor

### PR DESCRIPTION
**Pull request by devaigergely81**
The examples refactored and planned to put into the release:
* machine 1, 2 and 3
* train
* producer-consumer

Other examples that are not fixed in this branch and will not be part of the release:
* microwave
* garage
* printer

### CODE REVIEW

**Comment by devaigergely81** [comment]
@nboldi, @djnemeth, please review.

**Comment by nboldi** [comment]
It seems that XtxtUML cannot resolve the imports from the java files. I get a lot of errors like: `
Couldn't resolve reference to JvmDeclaredType 'hu.elte.txtuml.examples.producer_consumer.XProducerConsumer.Item'.` For imports, like: `import hu.elte.txtuml.examples.producer_consumer.XProducerConsumer.Item`

**Comment by devaigergely81** [comment]
@nboldi, did you use a guest Eclipse?

**Comment by nboldi** [comment]
Yes

**Comment by devaigergely81** [comment]
@kovacsgabor, please review the fixes for your comments. Do you have the problem reported by @nboldi?

**Comment by kovacsgabor** [comment]
No, I have no problem like that. The fixes are OK:

**Comment by kovacsgabor** [comment]
We agreed to merge.

**Comment by djnemeth** [comment]
> It seems that XtxtUML cannot resolve the imports from the java files. I get a lot of errors like:  Couldn't resolve reference to JvmDeclaredType 'hu.elte.txtuml.examples.producer_consumer.XProducerConsumer.Item'. For imports, like: import hu.elte.txtuml.examples.producer_consumer.XProducerConsumer.Item

@nboldi, did you use a wildcard import?

**Comment by nboldi** [comment]
I just imported the new models to Eclipse. Now with refreshing and cleaning everything, the errors vanished.

**Pull request merged**
