### PR TITLE
Pixel and Grid Widht/Height of boxes adjusted.

### PR DESCRIPTION
**Pull request by GregoBalu**
Fixes issue #242 .

### CODE REVIEW

**Comment by devaigergely81** [comment]
I have tested this fix with the following results:
- The diagram fragment posted in #242 looks like this with this branch:
diagrambug2

Problem seems to be solved, but I think the line is closer to the box than a grid unit.
- Now, by adding 1 character to the name of the top left box, we get:
diagrambug3

The line is touching the box again.

See the test project for experimentation: 
[Test.zip](https://github.com/ELTE-Soft/txtUML/files/131495/Test.zip)

**Comment by GregoBalu** [comment]
OK, so the fix I did was indeed needed, but one more thing used the grid/pixel ratio. The papyrus component when scaling, positioning and transforming the diagram pre-drawing. There the same error existed: basically the pixel/grid value was smaller than the actual value, therefore the diagram generated was squashed a bit.
After I fixed this, the given Test model seems to work fine whether you insert any number of 'a' letters into ones name or not.

**Comment by devaigergely81** [comment]
The fix seems to be OK.

**Comment by devaigergely81** [comment]
The branch is ready for merge.

**Pull request merged**
