### PR TITLE
XtxtUML overhaul

### LINKED ISSUE #384: Comprehensive unit test suite is needed for XtxtUML
In the current state of XtxtUML, the lack of unit tests is unacceptable. A comprehensive test suite has to be implemented as soon as possible.

### PR DESCRIPTION
**Pull request by djnemeth**
This pull request contains various improvements for XtxtUML, including
- minor fixes,
- refactoring,
- unit tests for critical runtime components,
- removal of unnecessary code, and
- documentation.

See the (full) commit messages for details. Resolves #384.

### CODE REVIEW

**Comment by djnemeth** [comment]
@nagyandras95 and/or @kmozsi, please review.

**Comment by djnemeth** [comment]
@kmozsi, it would be great if you could roughly verify that in the last commit, fbc24d7:
- name refactoring of test sources (enclosed within `'''` marks) is semantically consistent with their previous version,
- in each test case, 3rd arguments of `assertError` and `assertWarning` calls are unique.

**Comment by kmozsi** [comment]
Name refactoring in the last commit (fbc24d7) seems correct to me, and the mentioned arguments are unique.

**Comment by nagyandras95** [comment]
retest this please

**Pull request merged**
