### PR TITLE
Refactored InstanceCreator

### PR DESCRIPTION
**Pull request by nboldi**
Most of the checks are omitted because newInstance also does them (better than our code did). Recursive object creation is also eliminated as not used by now and (in my opinion) a very controversion "feature".

### CODE REVIEW

**Comment by devaigergely81** [comment]
@kovacsgabor, could you check this? I am surprised reading that "recursive object creation is ... not used by now". Is it not needed when creating instances of embedded classes during execution?

**Comment by kovacsgabor** [comment]
I created some tests and fixed some minor issues. @nboldi, please review my changes.

**Comment by kovacsgabor** [comment]
I added 3 line notes to the original commit. Please, review them too.

**Comment by nboldi** [comment]
Sorry for stupid git usage. Forgot that git does not give me the up-to-date version when using switch.

**Comment by kovacsgabor** [comment]
Now using different type of exceptions in different cases.

I think it is ready to be merged.

**Comment by nboldi** [comment]
Ok to merge, @devaigergely81?

**Comment by kovacsgabor** [comment]
We agreed to merge.

**Pull request merged**
