### PR TITLE
Split models

### PR DESCRIPTION
**Pull request by kovacsgabor**
See #56

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@gerazo, because of #164, the tests of the layout.export.tests project should be (temporarily) ignored. I could not achieve this, could you help, please?

**Comment by gerazo** [comment]
Hotfixed on master, see: https://github.com/ELTE-Soft/txtUML/issues/164

**Comment by gerazo** [comment]
It is ok now. Merge from master to correct his as well!

**Comment by devaigergely81** [comment]
All (to-be-released) examples are compiled and animated correctly now. A known issue in this branch is that wizards are incorrect, but there is a separate branch and pull request for that.

**Comment by devaigergely81** [comment]
I have reviewed the code as well, it looks OK.

**Pull request merged**
