### PR TITLE
Uml export hotfixes

### PR DESCRIPTION
**Pull request by nboldi**
Three simple fixes for three uml export issues.

### CODE REVIEW

**Comment by nagyandras95** [comment]
Is the request of `SendObjectAction` necessary to be a value pin? It does not contain `ValueSpecification` but it gets its value from an `OutputPin` through an `ObjectFlow`. Or could it contain a `ValueSpecification` like a literal integer not just an object?

**Comment by nboldi** [comment]
I have no control over the created input pin type. A literal expression is exported as a [ValueSpecificationAction](http://download.eclipse.org/modeling/mdt/uml2/javadoc/3.1.0/org/eclipse/uml2/uml/ValueSpecificationAction.html), that has a result output pin.

**Comment by devaigergely81** [comment]
The code changes seem OK to me.
@nagyandras95, please review if this works as expected and do merge if yes.
Thx.

**Comment by nagyandras95** [comment]
It seems OK to me too.

**Pull request merged**
