### PR TITLE
Layout export with sm diagrams

### LINKED ISSUE #118: Layout export is not exporting states and transitions
States and transitions are not exported as nodes and links, so the textual layout visualization of state machines (#4) cannot continue.

There are TODOs marking the missing parts as shown below:

layout_export_todo

@djnemeth @kovacsgabor

### PR DESCRIPTION
**Pull request by kovacsgabor**
Fixed #118 and generalized layout.export project to simplify the addition of new diagram types in the future. Also added tests.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
I added a new test project and some new tests, @gerazo, please review this (the last 4 commits).

**Comment by gerazo** [comment]
Outstanding! :+1:

**Comment by kovacsgabor** [comment]
@nboldi, could you review this branch, please? The last four commits were about to add the new test project properly as a Maven project, those have already been reviewed by @gerazo.

**Comment by nboldi** [comment]
I can only test because I'm not familiar with the design. So now it is possible to create a Diagram layout for a state machine? Can you give me an example to test?

**Comment by GregoBalu** [comment]
Not yet. The export (this) will process the definition of the SM layout description properly now. The actual arranging and visualizing part is yet to be done.
As far as I know this works well, but I cannot confirm it 100%.

**Comment by devaigergely81** [comment]
I have merged master into this branch in a local copy and found the following problems:
- Bundle 'org.eclipse.xtext.xbase.lib' cannot be resolved	MANIFEST.MF	/hu.elte.txtuml.xtxtuml.lib/META-INF	line 6	Plug-in Problem
- Project 'hu.elte.txtuml.layout.export.tests' is missing required library: 'D:\txtUML\eclipse-luna\plugins\com.google.guava_15.0.0.v201403281430.jar'	hu.elte.txtuml.layout.export.tests		Build path	Build Path Problem

**Comment by kovacsgabor** [comment]
I could not reproduce the above mentioned problems.

**Comment by kovacsgabor** [comment]
Is it OK to merge? As the split-models branch uses this one, it is a priority to merge this back into master.

**Comment by nboldi** [comment]
I see no objections to merging, but I'm not competent in the question.

**Comment by kovacsgabor** [comment]
@djnemeth, could you take a look on this branch?

**Comment by djnemeth** [comment]
I couldn't reproduce the [problem](https://github.com/ELTE-Soft/txtUML/pull/123#issuecomment-159855528) mentioned by devaigergely81. I've also checked the implementation and I think it's OK to merge. :+1:

**Pull request merged**
