### PR TITLE
Fix/issue1

### PR DESCRIPTION
**Pull request by dobreffandras**
#1 fixed

### CODE REVIEW

**Comment by devaigergely81** [comment]
I like the changes and have one more small request: Since these are user error messages, the
~~~~
+realException.getClass().getName()+ " thrown."
~~~~
part of the message could be omitted. The diagram name should not be in parentheses and the period (.) should be at the end of the first line.
arrangeerror

**Comment by dobreffandras** [comment]
Should the diagram name stay in the sentence as is, or would one of the followig examples look better:

... of diagram: testpkg.testdiag.
... of diagram "testpkg.testdiag".
... of diagram 'testpkg.testdiag'.

**Comment by devaigergely81** [comment]
I vote for the third option: ... of diagram 'testpkg.testdiag'.

**Comment by devaigergely81** [comment]
Tested, works fine. Thank you.

**Pull request merged**
