### PR TITLE
Renamed hu.elte.txtuml.export.uml2.tests.models_ as hu.elte.txtuml.export.uml2.tests.models

### LINKED ISSUE #290: Rename hu.elte.txtuml.export.uml2.tests.models_
Remove the underscore from the end.

### PR DESCRIPTION
**Pull request by kovacsgabor**
Resolves #290.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@nboldi, please review.

**Comment by gerazo** [comment]
As far as I know, Boldi used it because of technical reasons. Now I see that it is working even without the underscore. (This is kinda similar with what I am fighting now.)

**Comment by kovacsgabor** [comment]
Yes, he told me that the name without the underscore caused some problems before. I do not know what kind of problems were these, but everything seems to work now.

**Comment by nboldi** [comment]
If all unit tests pass then the problem was most likely in my configuration.

**Pull request merged**
