### PR TITLE
Microwave with gui

### LINKED ISSUE #494: Refresh the microwave oven example model with own images
Whoever takes this task, I will provide her/him with the original model and possibly with images.

### PR DESCRIPTION
**Pull request by kovacsgabor**
An updated version of #515. Resolves #494.

This pull request is based on #555 and #542, it already contains the commits of #555 and #542.

### CODE REVIEW

**Comment by djnemeth** [comment]
Do not merge this before #555.

**Comment by kovacsgabor** [comment]
retest this please

**Comment by kovacsgabor** [comment]
retest this please

**Comment by kovacsgabor** [comment]
retest this please

**Comment by djnemeth** [comment]
Visualization of the class diagram silently fails because both Papyrus and JavaScript wizards try to guess – using duplicated code – the underlying model of the layout description from its first annotation, which is `Spacing` here, containing no model information. The lesson here is that wizards should
1) not fail silently,
2) be able to detect the underlying model even in cases like above, and
3) be refactored to eliminate code duplication.

As far as I know wizards are being improved currently on a separate branch, so I suggest a simple reordering here.

Additionally, for some reason `SimpleClockSMDiagram` and `SmartClockSMDiagram` are visualized correctly with JavaScript, but with Papyrus they are displayed as empty diagrams labeled _StateMachine1_ and _StateMachine2_, respectively. @kovacsgabor, can you reproduce this?

**Comment by djnemeth** [comment]
@kovacsgabor has just told me that currently he can't access a developer environment to reproduce what I mentioned above. @szokolai-mate, @jtamas96, could you help us out? See the last paragraph of my previous comment.

**Comment by djnemeth** [comment]
@szokolai-mate, @jtamas96, any update on my previous request?

**Comment by jtamas96** [comment]
If I change StateMachineDiagram<Clock> to StateMachineDiagram<SmartClock> or StateMachineDiagram<SimpleClock> the diagrams are generated properly. Both SmartClock and SimpleClock extends Clock.

**Comment by djnemeth** [comment]
Nice catch! I don't think this is an error, as we want to visualize the state machines of the subclasses indeed, not the one that belongs to their super. Actually, I'm quite surprised that the JS visualization gets it right even with the `Clock` parameter.

**Pull request merged**
