### PR TITLE
Guard expression code export

### LINKED ISSUE #547: Guard constraints is not exported in case of diagram generation.
The constraint should be appared on the diagram as a textual java code.

### PR DESCRIPTION
**Pull request by nagyandras95**
I hope is resolves #547.

Supported guard activites: The guard blocks can contain only assigments, variable declerations and  return statements. The return expression can be arbitrary complicated.

### CODE REVIEW

**Comment by djnemeth** [comment]
@nagyandras95, it would be great if you could hide the many `instanceof` operators in `updateExpression` and `asString` under [Xtend's type-guarded switch expressions](http://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#switch-expression).

**Comment by djnemeth** [comment]
Something's wrong. I added boolean attributes `a`, `b` and `c` to `train.x.model.Engine` and guard `a && (b || c)` to `train.x.model.Engine.Stopped_Working` and then visualized the corresponding diagram with Papyrus. The exported guard is empty and the [stack trace](https://github.com/ELTE-Soft/txtUML/files/1910368/guard-trace.txt) shows an exception. This occurs without my recent commits too.

**Comment by djnemeth** [comment]
Jenkins, retest this please.

**Comment by nagyandras95** [comment]
retest this please

**Comment by djnemeth** [comment]
@nagyandras95, please review a8a92a4.

**Comment by nagyandras95** [comment]
It is OK for me.

**Pull request merged**
