### PR TITLE
Clock example

### PR DESCRIPTION
**Pull request by devaigergely81**
@kovacsgabor, please review.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
It is fine. However, I suggest waiting with this pull request for the #218, #220, #221 and #223 pull requests (all with small updates) to be merged, and then updating this example according to those changes.

**Comment by devaigergely81** [comment]
@jenkins, retest this please.

**Comment by devaigergely81** [comment]
@kovacsgabor, please re-review.

**Comment by kovacsgabor** [comment]
jenkins, retest this please

**Comment by kovacsgabor** [comment]
I had one minor problem with your code. Your solution depended on the right order of signals in which they arrive to the display. As txtUML execution is currently fully deterministic, it worked fine. I think, however, that we should provide completely valid example models.

Please, review my change.

**Comment by devaigergely81** [comment]
@kovacsgabor, your solution unfortunately misses midnight. :)
~~~~
23:59:56
23:59:57
23:59:58
23:59:59
23:59:1
23:59:2
~~~~
Another question: Why did each line of `Display.java` change? Is it a whitespace problem?

**Comment by devaigergely81** [comment]
@kovacsgabor, I combined your and my solution to solve both the "midnight problem" and the "signal ordering problem". Please review my patch!

**Comment by kovacsgabor** [comment]
Sorry for the error, this combined solution is fine.

**Pull request merged**
