### PR TITLE
Instead of interruption, an explicit check is performed in every iteration of ModelExecutorThread's loop

### LINKED ISSUE #112: Refactor thread handling
`Thread.interrupt()` should not be used as it may never actually interrupt the thread if it gets to work continously: https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html

### PR DESCRIPTION
**Pull request by kovacsgabor**
To fix #112.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@nboldi, please review.

**Comment by nboldi** [comment]
I think this would not work, since the runtime can be in a waiting state when calling inactivate. I already have another solution for this problem.

**Comment by nboldi** [comment]
See #127

**Comment by kovacsgabor** [comment]
> I think this would not work, since the runtime can be in a waiting state when calling inactivate. I already have another solution for this problem.

That is why I call interrupt() in inactivate.

**Comment by nboldi** [comment]
I see. The description suggested that this solution does not use interrupt, so I wasn't looking for it.

**Comment by kovacsgabor** [comment]
OK. Nevertheless, this fix is unnecessary as you implemented your one.

**Pull request closed without merging**
