### PR TITLE
Primitive parameters fix

### PR DESCRIPTION
**Pull request by kovacsgabor**
Solved #32

### CODE REVIEW

**Comment by nboldi** [comment]
I planned to use guava's `Primitives` class here. No need to reinvent the wheel. Even a small wheel.

**Comment by nboldi** [comment]
Of course it would mean that a new plugin dependency must be added to all project. Therefore I would wait for #18 with pulling this branch.

**Comment by devaigergely81** [comment]
If the team accepts guava as a dependency, we can introduce it to solve this issue as well. However, I consider this issue important (almost all users will bump into this), so I would give green light to this pull request as is.

**Comment by nboldi** [comment]
Ok. I think the whole `InstanceCreator` class needs to be refactored (it is a big spagetti), so this will be addressed then.

**Comment by kovacsgabor** [comment]
I opened a new issue for further work on this (#65).

**Pull request merged**
