### PR TITLE
Fix/issue98 crlf

### PR DESCRIPTION
**Pull request by devaigergely81**
This is intended to solve #98.
* Most of the changes are in generated files by Xtext. These are currently in the repos, therefore I decided to commit their changes. When we will have proper build environment, we might decide removing these generated sources.
* The XtxtUML-related part of the repos has CRLF line endings (including all the Xtext-generated files). I kept this encoding for now. (Actually, most of the commits in this branch is about restoring CRLF.) Later we should decide how to unify line endings in the repos and elaborate the necessary settings on developer machines.
* The changes in non-generated files are:
  * `XtxtUML.xtext`: The grammar has been changed to support transitions in states.
  * `XtxtUMLValidator.xtend`: Validation for duplicate transitions needed to be changed accordingly.
  * A `.gitignore` file has been added in the `hu.elte.txtuml.utils.tests` project in order to make git put the src directory under version control. This eliminates a build error in this project, and is independent of #98.

### CODE REVIEW

**Comment by devaigergely81** [comment]
@kmate and/or @djnemeth, please review!

**Comment by djnemeth** [comment]
Seems to be working. I have tested the grammar, the previously improper inner transition execution and the adjusted duplicate name validation.

It's nice to see how we hadn't had to modify the model inferrer, thanks to the use of Xtend's dispatch methods.

**Comment by kmate** [comment]
I think we should not merge back this branch, as it corrupts the history of the whole xtext language definition file. Please apply these changes on a fresh branch eg. using a patch.

**Comment by devaigergely81** [comment]
OK, I'll redo this on another branch.

**Pull request closed without merging**
