### PR TITLE
Deva/sm diagrams

### PR DESCRIPTION
**Pull request by dobreffandras**

### CODE REVIEW

**Comment by kovacsgabor** [comment]
ok to test

**Comment by kovacsgabor** [comment]
@GregoBalu, some layout visualizer tests fail on this branch after the merge from master. Could you take a look on this problem?

**Comment by GregoBalu** [comment]
One of the tests were to strict, the problem was that the links route were (1, -1) away from where I calculated them. This is because this branch handles things a little different when arranging. The tests are "fixed" (generalized) now.

**Comment by kovacsgabor** [comment]
retest this please

**Comment by kovacsgabor** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Comment by gerazo** [comment]
retest this please

**Comment by kovacsgabor** [comment]
I do not have to review pull requests now, but this should be merged soon. @ELTE-Soft/all, please review!

**Comment by djnemeth** [comment]
[This](https://github.com/ELTE-Soft/txtUML/tree/0f27a961e1c95db5696904a30d426d96fa9d5fb1/examples/demo) looks strange. Is it intentional?

**Comment by dobreffandras** [comment]
No, the folders beginning with "hu.elte...." should not be there I think.

**Pull request merged**
