### PR TITLE
Cpp hotfixes

### LINKED ISSUE #567: C++ tests make the Maven build fail under Linux
See the attached build log: [maven-build-log.txt](https://github.com/ELTE-Soft/txtUML/files/1778542/maven-build-log.txt)

Build environment (Local / Jenkins):
- Ubuntu 17.10 / 16.04.3 LTS
- Maven 3.5.0 / 3.3.9
- LLVM 4.0.1 / 3.8.0
- clang 4.0.1-6 / 3.8.0
- g++ 7.2.0 / 5.4.0
- gcc 7.2.0 / 5.4.0
- ninja 1.7.2 / 1.5.1
- cmake 3.9.1 / 3.5.1

Steps to reproduce:
1. Download master
1. Run `mvn clean verify` in `dev/releng/hu.elte.txtuml.parent/`

### PR DESCRIPTION
**Pull request by nagyandras95**
This PR contains:

- Not show desktop after generation under linux (it crashes anyway)
- Make singelton thread safe (fixes #567) 
- Tryes to fix producer_consumer dedlock issue

### CODE REVIEW

**Comment by djnemeth** [comment]
Jenkins, retest this, please.

**Comment by nagyandras95** [comment]
retest this please

**Comment by nagyandras95** [comment]
retest this please

**Comment by nagyandras95** [comment]
retest this please

**Comment by nagyandras95** [comment]
retest this please

**Comment by djnemeth** [comment]
@kmozsi, please help me with the review.

**Pull request merged**
