### PR TITLE
Composition

### PR DESCRIPTION
**Pull request by nboldi**

### CODE REVIEW

**Comment by kovacsgabor** [comment]
To follow the current structure of the modeling API, I would suggest ```Container``` to be an inner class of ```Composition```.

**Comment by nboldi** [comment]
@kovacsgabor, @devaigergely81, please merge if ready.

**Comment by kmate** [comment]
Maybe the JVM model inference in XtxtUML should also be updated to these changes.

**Comment by kovacsgabor** [comment]
I added some JavaDoc fixes and changed the multiplicity of ```Container``` ends to 0..1. (They have 0..1 multiplicity in the UML standard as stated by @devaigergely81 at the #138 issue.) I also asked a question at the corresponding issue.

Apart from these, the branch seems to work fine. I reviewed the changes made by @nboldi (I am not competent in the XtxtUML part updated by @kmate) and tested all implemented functionalities.

**Comment by kmate** [comment]
As the class reference is updated in JVM model inferer, I think no further actions are needed in XtxtUML. I also confirm the merge.

**Comment by devaigergely81** [comment]
I think it is fine to merge. Could you have a look at my commit 6ff67b3086b32e02410cad987895d95c7b17a9d4 please before merging?

**Comment by kovacsgabor** [comment]
:+1: Fine to merge.

**Pull request merged**
