### PR TITLE
Protected visibility is allowed in JtxtUML

### LINKED ISSUE #344: Declaration of protected member causes error in generated Java file
The following valid xtxtuml code:
```
   package [...]
   class Test {
      protected String a;	
      protected void foo() { }
   }
```
Causes error "Invalid modifier. Only private and public are allowed on all elements." in the generated Java file. 

You can easily reproduce it, for instance, in the monitoring example by making Alert.max protected.

### PR DESCRIPTION
**Pull request by kovacsgabor**
To fix #344.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
@nboldi, please review.

**Comment by kovacsgabor** [comment]
retest this please

**Comment by kovacsgabor** [comment]
retest this please

**Comment by nboldi** [comment]
@kovacsgabor Seems ok for me. If you tested it, you can merge.

**Comment by kovacsgabor** [comment]
Yes, I tested it.

**Pull request merged**
