### PR TITLE
Validation of box types

### PR DESCRIPTION
**Pull request by nboldi**
Modified validation to enable Integer, Boolean and Double types as attributes or method parameters. Corrected two examples.

### CODE REVIEW

**Comment by nboldi** [comment]
@devaigergely81, please review

**Comment by devaigergely81** [comment]
Do we handle the boxed types when exporting UML models?

**Comment by nboldi** [comment]
Yes

**Comment by devaigergely81** [comment]
XtxtUML validation also needs to be changed to keep them in synch. Please also change the validation error messages, like in https://github.com/ELTE-Soft/txtUML/commit/d1563dbbb49287a0af836f5095fded7ea76cb715.
@djnemeth, @nboldi, please decide who takes the XtxtUML part.

I close the pull request for now.

**Comment by djnemeth** [comment]
As I can see, we allow external types in signal attributes and constructor parameters (see [SignalVisitor.java:26](https://github.com/ELTE-Soft/txtUML/blob/d1563dbbb49287a0af836f5095fded7ea76cb715/dev/plugins/hu.elte.txtuml.validation/src/hu/elte/txtuml/validation/visitors/SignalVisitor.java#L26), [SignalVisitor.java:48](https://github.com/ELTE-Soft/txtUML/blob/d1563dbbb49287a0af836f5095fded7ea76cb715/dev/plugins/hu.elte.txtuml.validation/src/hu/elte/txtuml/validation/visitors/SignalVisitor.java#L48) and [Utils.java:56](https://github.com/ELTE-Soft/txtUML/blob/d1563dbbb49287a0af836f5095fded7ea76cb715/dev/plugins/hu.elte.txtuml.validation/src/hu/elte/txtuml/validation/visitors/Utils.java#L56)). Shouldn't we permit basic types and datatypes only here?

**Comment by kovacsgabor** [comment]
What is the status of this branch now? Do we plan to finish it? Or should it be deleted?

**Pull request closed without merging**
