### PR TITLE
Upgrade to Neon.2

### LINKED ISSUE #389: Migrate to Neon
As Neon, the latest Eclipse version is out, we shall investigate what changes are necessary to make txtUML compatible with it.

### PR DESCRIPTION
**Pull request by zsgyulavari**
I believe that this can be merged. Resolves #389.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
When will this pr be merged?

**Comment by dobreffandras** [comment]
Needs a review if the xtext and papyrus dependent parts are working fine, but after that it can be merged.

**Comment by dobreffandras** [comment]
I realized that with the new target definitions (Papyrus 2.0.2) the diagram generation takes forever. A thread deadlock occurs somehow. (With Papyrus 2.0.0 it works fine)
@djnemeth  or @kovacsgabor please confirm if you can reproduce this bug.
_Reproduction steps_: Launch a guest Eclipse.  Try to visualize some diagrams (e.g. machine1.j.Machine1ClassDiagram). The progress bar will not move, visualization will stuck.
(_Note_: For debugging place a breakpoint on [EditorOpener Line 31](https://github.com/ELTE-Soft/txtUML/blob/neon-upgrade/dev/plugins/hu.elte.txtuml.export.papyrus/src/hu/elte/txtuml/export/papyrus/utils/EditorOpener.java#L31). Eclipse is unable to open the editor.)

**Comment by dobreffandras** [comment]
Somehow running the visualization with a ProgressService caused a deadlock. It could be fixed with running a job on the UI thread. Side-effect: because the whole process runs on the UI thread, no progress bar opens.

**Comment by kovacsgabor** [comment]
ok to test

**Comment by djnemeth** [comment]
> It could be fixed with running a job on the UI thread. Side-effect: because the whole process runs on the UI thread, no progress bar opens.

That's really unfortunate. Do we have any other options?

**Comment by dobreffandras** [comment]
In the [new/papyrus-export](https://github.com/ELTE-Soft/txtUML/tree/new/papyrus-export) branch only a minor part of the visualization process runs on the UI thread so the progress dialog is displayed correctly. That implementation has to be tested as well however, because there were some changes in the progress monitoring mechanism in Eclipse 4.X (see [1](https://eclipse.org/articles/Article-Progress-Monitors/article.html), [2](http://www.vogella.com/tutorials/EclipseJobs/article.html)).

**Comment by djnemeth** [comment]
> In the new/papyrus-export branch only a minor part of the visualization process runs on the UI thread so the progress dialog is displayed correctly.

This will do it, thanks!

**Comment by djnemeth** [comment]
Before we can merge this pull request, we have to manually verify that everything is working correctly on the new target platform. The members responsible for testing txtUML components under Neon.2 are:
- JtxtUML: @kovacsgabor,
- XtxtUML: @djnemeth,
- UML export and visualization: @devaigergely81,
- C++ export: @nagyandras95,
- demo examples, state machine animation, debug functions: @kmozsi.

Using a runtime Eclipse should be enough. Don't forget to set the [new target platform](https://github.com/ELTE-Soft/txtUML/blob/f40fa7a65f68c0beff7f57196dfdc83123f438c6/dev/releng/hu.elte.txtuml.target/mirrors.target). Please drop a brief report here after you're done.

**Comment by dobreffandras** [comment]
Jenkins, retest this, please.

**Comment by djnemeth** [comment]
Jenkins, retest this, please.

**Comment by djnemeth** [comment]
I have tried XtxtUML functionalities – especially the UI-related parts – using the demo models and some manual testing in a runtime Eclipse. Apart from a small bug in the formatter (see ef2a899), everything seems to be working.

**Comment by devaigergely81** [comment]
Multiplicities and labels are misplaced on class diagrams. @dobreffandras, does this happen also in case of the new diagram generation branch?

**Comment by devaigergely81** [comment]
State charts are also problematic:
image
Even more interesting, if one starts scrolling at the side of the enclosing box:
image

**Comment by devaigergely81** [comment]
Regarding diagram generation I suggest that we test the merge of the Neon upgrade and the New Papyrus visualization branches to see if the above mentioned problems get resolved there.

**Comment by dobreffandras** [comment]
The `new/papyrus-export` branch is not updated for Neon.2 for the time being. Hence comparison of the two is not suitable.

I could reproduce the two issues on this branch:
1. Labels aligned inappropriately
Papyrus 2.0 generates an `IS_UPDATED_POSITION` flag and a location for every decoration (e.g.: multiplicity, name, role, sterotype etc.) of the links into the notation markup. However I couldn't find out the consistent functioning of this, setting the flag `false` and deleting the generated layout constraints solves the issue.
I could not test the effect of this on the `new/papyrus-export` branch. My assumption is that it will not be an issue there because no layout constraint is generated for the decorations on that branch.

2. Scrolling a StateMachine
I built up a StateMachine manually. It has to be a Papyrus bug, because the problem is the same for that diagram, see the image below
papyrus_bug

**Comment by dobreffandras** [comment]
I made a little workaround about the inappropriately positioned labels. They are now repositioned to the relative (0,0).

**Comment by nagyandras95** [comment]
The part of C++ export seems to OK.

**Comment by kmozsi** [comment]
I have manually tested the demo examples, state machine animation and debug functions, everything seems OK to me. During the test I have found a bug (#501), but it is not related to neon.

**Comment by djnemeth** [comment]
@dobreffandras, does 96e9986 make this mergeable regarding visualization?

**Pull request merged**
