### PR TITLE
Ports in XtxtUML

### LINKED ISSUE #190: Support for ports and connectors in XtxtUML
Dependent on #189.

### LINKED ISSUE #227: Trigger with port in XtxtUML
See #212.

The supposed XtxtUML syntax is the following:
```
transition t {
  from /* ... */;
  to /* ... */;
  trigger MySignal;
  port MyPort;
}
```

### PR DESCRIPTION
**Pull request by djnemeth**
#### New XtxtUML features:

- **Port-related language elements.** [behavior] ports (without multiplicities), interfaces, (delegation | assembly) connectors (without connector end multiplicities), port restriction of transition triggers, port access expression, signal sending to port.

 Syntax:
 - Ports:

        ```
        class A {
            [behavior] port P {
                [provided I1;]
                [required I2;]
            }
        }
        ```
 - Interfaces:

        ```
        interface I {
            reception S1;
            reception S2;
            reception S3;
            // ...
        }
        ```
 - Connectors:

        ```
        (connector | delegation) C {
            roleA->portA endA;
            roleB->portB endB;
        }
        ```
 - Port restriction of transition triggers:

        ```
        transition T {
            // ...
            trigger S1;
            [port P;]
        }
        ```
 - Port access expression:

        ```
        this->(port);
        ```
 - Signal sending to port:

        ```
        send new S() to portInstance;
        ```
- **Validation for new language elements.** See method signatures of [XtxtUMLPortValidator.xtend](https://github.com/ELTE-Soft/txtUML/blob/97be278db7abd7805b60ae42bc158378d722def1/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/validation/XtxtUMLPortValidator.xtend) or [line 319](https://github.com/ELTE-Soft/txtUML/blob/97be278db7abd7805b60ae42bc158378d722def1/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/validation/XtxtUMLValidator.xtend#L319) and [line 357](https://github.com/ELTE-Soft/txtUML/blob/97be278db7abd7805b60ae42bc158378d722def1/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/validation/XtxtUMLValidator.xtend#L357) of [XtxtUMLValidator.xtend](https://github.com/ELTE-Soft/txtUML/blob/97be278db7abd7805b60ae42bc158378d722def1/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/validation/XtxtUMLValidator.xtend) for a brief overview of the implemented checks.
- **Labeling for new language elements.**

 port interface
 assembly_delegation port_restriction

#### Other changes:
- **Added XtxtUML version of port examples.** Examples *Clock* and *PingPong* are now available in XtxtUML syntax as well.
- **Fixed labeling of compositions.**

 composition
- **Various fixes and modifications.** See the (full) commit messages for details.

<hr>

The merge of this pull request:
- resolves #190,
- resolves #227,
- potentially affects #145 and #216.

### CODE REVIEW

**Comment by djnemeth** [comment]
@devaigergely81 and @kmate, please review.

**Comment by kmate** [comment]
I hope I will have some time to check this in the afternoon.

**Comment by kovacsgabor** [comment]
#216 will become invalid when this pull request is merged.

**Comment by kmate** [comment]
All changes seem to be reasonable and correct. I tried out the clock example and it works well. I also made some random testing on validation and it worked as expected. I confirm the merge, but as it contains a huge number of changes, maybe another team member should confirm it.

**Comment by kovacsgabor** [comment]
I tested it in a guest Eclipse and also installed it from the generated update site. Both works properly.

I looked at the generated JtxtUML code of the examples too. It seems to be fine as well.

**Comment by devaigergely81** [comment]
Good job! :-)

**Pull request merged**
