### PR TITLE
Diagram and cpp generation wizard improvements

### PR DESCRIPTION
**Pull request by kmozsi**
Features included:
- Packages are filtered in the model browser dialogs, only model packages (and subpackages) are visible.
- Diagram description and c++ configuration selection is also filtered.
- Allow to choose multiple diagram descriptions to visualize.
- Diagram selection is directly in the wizard instead of a new dialog - tree selection view.
- Allow to select diagram layouts and c++ configurations from different java projects (than the model package).

### CODE REVIEW

**Comment by dobreffandras** [comment]
Seems to be working fine, but:

- Is it intended that the subpackages of the model are also listed? If I'm not mistaken @kovacsgabor  said that it took him effort to implement this feature, so eliminating it is theoritically not a big issue.

- I've found another issue concerning the checkboxes. If the window is reopened and all items under a package is checked the the package is not checked but marked with a box. See the picture.

issue

- The checkmarks are looking weird by the way, but I think that is not our fault, am I right?

**Comment by kovacsgabor** [comment]
> Is it intended that the subpackages of the model are also listed? If I'm not mistaken @kovacsgabor said that it took him effort to implement this feature, so eliminating it is theoritically not a big issue.

As Java in fact does _not_ know the term "subpackage", we do this:

1. Search for txtUML models, that is, Java packages that have a `package-info.java` file in which the package is annotated with the `hu.elte.txtuml.api.model.Model` annotation.
2. Search for all subpackages of txtUML models, that is, Java packages whose name is like `x.y` where `x` is the name of a txtUML model.

So yes, retrieving _only_ the models themselves should be easy by performing only the first step.

**Comment by dobreffandras** [comment]
The two fixes are fine. 

Somehow the checkmarks are looking good for me as well right now:
checkbox

The diagram description windows are reviewed and able to merge. @nagyandras95 please take a look at the cpp generation wizard.

**Comment by kmozsi** [comment]
@dobreffandras, thanks for the review. 
The last two commits resolve these issues except the last one, which might be platform-specific, because I haven't encountered this problem. As you said, it is not our fault, as checkmarks are drawn by the Tree widget of CheckboxTreeViewer using OS calls.

**Comment by djnemeth** [comment]
Did this resolve #438?

**Comment by dobreffandras** [comment]
I think yes, it did. For the diagram descriptions at least:
- only model packages are listed in the model selection dialog
- only diagram descriptions (grouped by projects) are listed where you want to select the diagram descriptions.

@nagyandras95 what about the configurations?

**Comment by dobreffandras** [comment]
I've found a bug. When the user clicks the browse button for the model selection the UI behavior gets corrupted in the case when the project name is empty. It's because the project searching throws an unchecked exception which wasn't handled. 

I fixed this bug. At the same time a took a look at the Cpp wizard. This issue resolves #438.

**Comment by kmozsi** [comment]
> Did this resolve #438?

Currently I am working on the 'visualize' context menu, which is mentioned in #438. 
This pull request does not contain that feature, so it resolves the issue only partially. 

@dobreffandras, thanks for the bugfix.

**Comment by dobreffandras** [comment]
I created a new issue about the mentioned context menu

**Comment by nagyandras95** [comment]
The cpp wizard is listing only the model packages and the configuration classes, so this part seems to OK for me.

**Pull request merged**
