### PR TITLE
Revert visualization refactoring

### PR DESCRIPTION
**Pull request by djnemeth**
This reverts #587 as it has been accidentally merged.

### CODE REVIEW

**Comment by djnemeth** [comment]
@szokolai-mate, please verify that this reverts all the changes you made in #587. @kmozsi and @jtamas96, please check that this doesn't affect the recently merged #574. I'll try to look into everything else.

**Comment by szokolai-mate** [comment]
I can confirm that changes in #587 are absent.
I also think changes from #574 were keps, as desired, but I would like confirmation.

**Comment by djnemeth** [comment]
@jtamas96, please also verify both code and functionality.

**Comment by djnemeth** [comment]
Thanks for your quick reviews. General functionality also seems to be in order, so I'm doing the merge.

**Pull request merged**
