### PR TITLE
New/layout visualizer tests

### PR DESCRIPTION
**Pull request by GregoBalu**
Added Unit tests for the layout.visualizer plugin.

### CODE REVIEW

**Comment by kovacsgabor** [comment]
jenkins retest this please

**Comment by devaigergely81** [comment]
The branch looks OK except the following: After running a full build with the tests, the workspace becomes dirty because of a new directory is created with class files inside: `/tests/hu.elte.txtuml.layout.visualizer.tests/bin/`
I think that tests should clean up the temporal stuff they use. @gerazo, what's your say?

**Comment by gerazo** [comment]
I agree. No files should be created by any build which is not ignored by git (or cleaned up even in case of test failure). This can be important also for the automatic build system not to mention the frustration caused for human developers :hamster:

**Comment by devaigergely81** [comment]
@GregoBalu, I close the pull request for the moment, please open a new one when the above issue gets fixed. Thank you!

**Comment by GregoBalu** [comment]
[How to create a test project](https://github.com/ELTE-Soft/txtUML/wiki/Creating-Projects#creating-a-test-project)
[Instructions were unclear](http://vignette2.wikia.nocookie.net/candycrushsoda/images/2/22/Instructions_unclear.png/revision/latest?cb=20150911021005)

**Comment by devaigergely81** [comment]
:D Welcome to improve the instructions! :)

**Pull request closed without merging**
